language: ruby
rvm: 2.1

env:
  global:
    - secure: "eLpmPNM+ganpcC2HazUgy3LfyoPLrg1YFve/R7M3onY72P8kfMDqc2VrLMhSZ1+ncYWVp71QXRIz5rqaa7Ft9EqbriVdVSsP/8SXAINauyJjENLg3qSyd5slmslpHLAZN4ayepj7UrJivwZktZpKwkvfEFyuN6dThaqBDxqj3BWRlTmzTRQQaNf9vXeODTSEjF1mcL5bZdBcKJOO6siZaENkem7KvfzkY7e491ECSiFgDWq50VUSgB4vN2Zunb2VhpVqm9KnoSGq+83/w3CN+4hhyDm1kRLkvuxILtjoSv+ej/DElk8AmtjBrZsoE7JAXn49BySkjOepOUhqg2HRXyEcrUtA5Vy6OexBCf8jD38hSuA/y79sBZxjuQoioGYVbQR35mSFjTuj22po/8Wx5TLWU7QD8Az7qPbmGgFmYQ5lyDj13Sh45AdMy84jAj6Jt42UmeStcQGdj9qq2hONRmOj/tNz27EqB7iMxZjtk4dxeU7zD15dgHvEwYr+LqMjU7VfTInSDACbe8Uy0u2ZbDASevRtn/LdzTRvjZaXIKyTaFTTUG/JLi4RHXIrG169l9aonaatE7qQ1soSaE2aY2E3QtkD+bj9oKTvKkswsDon1f/GekVL/RDIVi+6zYPahiI8C4j/VBa/K3GkLxlwsb0VRzqUnjB2xm3iSx66YbQ="
    - secure: "sTMh1ZphVjXT5g+zPHPLK6ZE5VrCXg/ITlvfv5fDs1xMiY3hI758180OAqlKGjS5I4F6N8Kd/e9whQMK6ckCIV0HFqu/jdyalSxFyZktoZoZrBotD+megSGjZXPrJN5d3Q6oF3na8tmt0/rRX0rFIQY6eDwbEq8jjDll7aUir5hR8BMVXDr2uFwGy7tgkKp1ZN3+fhuUoYpmU2A5YVWgl0EzScgZgY5gEKR1rc2AstkuJFpmxLLQSwp3tVAP8bcARMv9OoTa0b1UhIhQQ79+SnX6WiZIU/XkYGCvPyiDwhod7SJKO44nnGJNB3hF54lB52atmMdCUjXFIHXNoeMndPVQ8qrPZF/ZyWdDa5eirjvQb2iAJEU4M8u36O8Gu7x3suT406jyvtWCIPn0vSYidPVOAPkUQWH0yJeTEdEyyWLl3PD9ltJGTiGHvZnMDmMjyW5/JkvcNZKvgaYzXknz0FeFBncATuW+Mp8aFoBobl/nIuKB5pCLvcVKlPEPkcmwaok16ioJziJSdYAtnPwWNldT5OS9szXIvI3z0SQXmfaXpGipdSLCuudpoITceg4Ak0HGwU8gTdEwDdWdxTXoVLDaUh5+3GWaSRlEl7AlIqFn57IllpWRVN/uNmfLAwydQWXRfUNN2b8fFu11vGk5Pz+nuRsim7rsHdCKo1KDiMI="

script:
  - bundle install
  - bundle exec rackup -p 8001 > /dev/null &
  - bash run_local.bash
  - bundle exec rspec spec/welcome.rb
