language: ruby
rvm: 2.1

env:
  global:
    - BROWSERSTACK_USER=browserstackrunn1
    - BROWSERSTACK_ACCESS_KEY=5njsGyzgj6JV2hwyHutq

# new Travis DSL
addons:
  browserstack:
    username: browserstackrunn1
    access_key: 5njsGyzgj6JV2hwyHutq
  browserStack:
    username: browserstackrunn1
    access_key: 5njsGyzgj6JV2hwyHutq
  firefox: "39.0"

script:
  - bundle install
  - bundle exec rackup -p 8001 > /dev/null &
  # - bash run_local.bash
  - bundle exec rspec spec/welcome.rb
